// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfv24yXtdbjD5VHnzO2toyRnjUNsC9Jkk',
    appId: '1:791994735454:web:abc8cd1e129f73d0860dcf',
    messagingSenderId: '791994735454',
    projectId: 'upload-16126',
    authDomain: 'upload-16126.firebaseapp.com',
    storageBucket: 'upload-16126.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiIhoL3NttjwYF5RGfMAJSGrQESS_X0KY',
    appId: '1:791994735454:android:f6ce50658c310fd9860dcf',
    messagingSenderId: '791994735454',
    projectId: 'upload-16126',
    storageBucket: 'upload-16126.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATywImtP0Mp42RdDiC6KVCsgHnsMcJM9I',
    appId: '1:791994735454:ios:d072a41508ba414e860dcf',
    messagingSenderId: '791994735454',
    projectId: 'upload-16126',
    storageBucket: 'upload-16126.firebasestorage.app',
    iosBundleId: 'com.example.uplaodProfile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATywImtP0Mp42RdDiC6KVCsgHnsMcJM9I',
    appId: '1:791994735454:ios:d072a41508ba414e860dcf',
    messagingSenderId: '791994735454',
    projectId: 'upload-16126',
    storageBucket: 'upload-16126.firebasestorage.app',
    iosBundleId: 'com.example.uplaodProfile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfv24yXtdbjD5VHnzO2toyRnjUNsC9Jkk',
    appId: '1:791994735454:web:e5ed47d4658d97f0860dcf',
    messagingSenderId: '791994735454',
    projectId: 'upload-16126',
    authDomain: 'upload-16126.firebaseapp.com',
    storageBucket: 'upload-16126.firebasestorage.app',
  );

}